FROM golang:1.19.4-alpine3.17 AS build_base

# Set the Current Working Directory inside the container
WORKDIR /tmp/go-output

# We want to populate the module cache based on the go.{mod,sum} files.
copy go.mod .
copy go.sum .

RUN go mod download

COPY . .

# Build the Go app
RUN go build ./cmd/alive-agent/

# Start fresh from a smaller image
FROM alpine:3.17
RUN apk add ca-certificates

COPY --from=build_base /tmp/go-output/alive-agent /app/alive-agent

EXPOSE 8080
ENTRYPOINT ["app/alive-agent"]