version : 3.9

services :
  prometheus :
    image: bitnami/prometheus:latest
    command:
      - '--config.file=/etc/alive-example/prometheus.yml'
      - '--storage.tsdb.path=/opt/bitnami/prometheus/data'
      - '--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries'
      - '--web.console.templates=/opt/bitnami/prometheus/conf/consoles'
    network_mode: host
    # ports:
    #   - 9090:9090
    volumes:
      - ./example/prometheus-persistence:/opt/bitnami/prometheus/data
      - ./example:/etc/alive-example

  # grafana:
  #   image: grafana/grafana
  #   user: "472"
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - grafana_data:$HOME/opt/grafana/
  #     - ./grafana/provisioning/:$HOME/opt/grafana/provisioning/
  #   # env_file:
  #   #   - ./grafana/config.monitoring
  #   restart: always