version : 3.9

services :
  prometheus :
    image: bitnami/prometheus:latest
    command:
      - '--config.file=/etc/alive-example/prometheus.yml'
      - '--storage.tsdb.path=/opt/bitnami/prometheus/data'
      - '--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries'
      - '--web.console.templates=/opt/bitnami/prometheus/conf/consoles'
      - '--log.level=debug'
    network_mode: host
    # ports:
    #   - 9090:9090
    volumes:
      - ./example/prometheus-persistence:/opt/bitnami/prometheus/data
      - ./example:/etc/alive-example

  # grafana:
  #   image: grafana/grafana
  #   user: "472"
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - grafana_data:$HOME/opt/grafana/
  #     - ./grafana/provisioning/:$HOME/opt/grafana/provisioning/
  #   # env_file:
  #   #   - ./grafana/config.monitoring
  #   restart: always

  # podman create --name=alive_prometheus_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=alive --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=alive --label com.docker.compose.project.working_dir=/home/gio/dev/alive --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=prometheus --network host -v /home/gio/dev/alive/example/prometheus-persistence:/opt/bitnami/prometheus/data -v /home/gio/dev/alive/example:/etc/alive-example --network-alias prometheus bitnami/prometheus:latest --config.file=/etc/alive-example/prometheus.yml --storage.tsdb.path=/opt/bitnami/prometheus/data --web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries --web.console.templates=/opt/bitnami/prometheus/conf/consoles --log.level=debug