name: wejick-alive-agent # you probably want to 'snapcraft register <name>'
base: core20
version: '0.1'
summary: Agent of alive monitoring system
description: |
  Agent of alive monitoring system

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  alive-agent:
    plugin: go
    source-type: git
    source: https://github.com/wejick/alive

apps:
  alive-agent:
    command: bin/alive-agent