name: build-publish-image
run-name: ${{github.actor}} is building and publishin image
on:
  release:
      types:
        - created
  workflow_dispatch:
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set variables
        run: |
          echo "VERSION-SERVER=$(cat ./cmd/alive-server/version.txt)" >> $GITHUB_ENV

      - name: build-image-server
        id: build-image-server
        uses: redhat-actions/buildah-build@v2
        with:
          image: alive-server
          tags: latest ${{ env.VERSION-SERVER }}
          containerfiles: |
            ./dockerfile.server