name: build-publish-image
run-name: ${{github.actor}} is building and publishin image
on:
  release:
      types:
        - created
  workflow_dispatch:
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set variables
        run: |
          echo "VERSION-SERVER=$(cat ./cmd/alive-server/version.txt)" >> $GITHUB_ENV

      - name: build-image-server
        id: build-image-server
        uses: redhat-actions/buildah-build@v2
        with:
          image: alive-server
          tags: latest ${{ env.VERSION-SERVER }}
          layers: true
          containerfiles: |
            ./dockerfile.server
      
      - name: push-server-to-ghrc
        id: push-server-to-ghrc
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ steps.build-image-server.outputs.image }}
          tags: ${{ steps.build-image-server.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"