name: go-test
run-name: ${{github.actor}} is testing alive
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    - uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
          cache: true
    - uses: actions/checkout@v3
    - name: build
      run: go build -v ./...
    - name: test
      run: go test -v ./...